---
# tasks file for prometheusrole

- name: Ensure prometheus user exists
  ansible.builtin.user:
    name: prometheus
    shell: /bin/false

- name: Create Prometheus installation directory
  ansible.builtin.file:
    path: "{{ prometheus_install_path }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
    dest: "{{ prometheus_install_path }}"
    remote_src: yes

- name: Set up Prometheus configuration
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_install_path }}/prometheus.yml"
  notify:
    - restart prometheus

- name: Create systemd service file for Prometheus
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      ExecStart={{ prometheus_install_path }}/prometheus --config.file={{ prometheus_install_path }}/prometheus.yml
      Restart=always
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service
  notify:
    - restart prometheus

- name: Start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
